import "./globals.css";

export const metadata = {
  title: "I wonder what this does",
  description: "Generated by I wonder what this does",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <h1>Just an additional h1</h1>
        {children}
      </body>
    </html>
  );
}
